### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/transit#6]
For https://github.com/ycoady/UVic-Software-Evolution/issues/15

| Story | Value | Estimate | Risk | Asssigned | Goal Time |
| :-- | :-: | :-: | :-: | :-: | :-- |
| ~~Threading~~ | 20 | 30 | Medium | @hoverbear | April 30 |
| Rust Language-Support | 50 | 70 | Medium | @BrodyHolden | April 30 |
| JS Language-Support | 50 | 70 | Medium | @BrodyHolden | April 30 |
| Rust Web UI | 20 | 40 | Low | @hoverbear | April 30 |
| Stability Improvements against panics | 40 | 20 | Low | Both | April 30 |

**Comment by Hoverbear** [comment]
Would be super cool if it streamed results instead of batching them!

**Comment by BrodyHolden** [comment]
+1 streamed results.

**Comment by Hoverbear** [comment]
Threading will not be happening on a processing front since it's pointless. `libgit` itself is not threadsafe and the benefits are not worth the thread synchronization cost.
