### ISSUE TITLE
Output format for `--web`

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/transit#8]
I was thinking of showing Additions/Deletions/Moves in a graph for comparative analysis and better data relevance.

I'd propose something like:

``` rust
/// The results between a pair of commits.
#[derive(Debug, RustcEncodable)]
pub struct OutputSet {
    old: TransitOid,
    old_time: i64, // Seconds from Epoch
    new: TransitOid,
    new_time: i64, // Seconds from Epoch
    additions: Vec<Output>,
    deletions: Vec<Output>,
    moves: Vec<Output>,
    author: String,
}

/// The result of a single diff.
#[derive(Debug, RustcEncodable)]
pub struct Output {
    old_filename: String,
    new_filename: String,
    origin_line: u32,
    destination_line: u32,
    lines: Vec<String>,
}
```

Considerations:
- Does `destination_line` or `origin_line` matter in the case of an addition or deletions?
- Returning the `lines` instead of the `num_lines` will be more resource intensive, but allow for extension to actually view different additions/deletions/moves in the browser. Not sure if we have time for that though.
- The `additions` and `deletions` returned will be less the `moves`.
- This won't harm the command line output at all.
- Would it be useful to output the author of a particular change as well?

cc @devinc13: What do you think?

Helps #6.

**Comment by devinc13** [comment]
Sorry, my email filtered this out! Looks good! We're just using the command line output, so it won't change what we're doing! Some of your considerations could lead to cool other projects, like the author idea (something about how many lines are moved by each contributor compared to ... something else!).

**Comment by Hoverbear** [comment]
@BrodyHolden What do you think of this?
